spring:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # query? ??? ??? ??
        default_batch_fetch_size: 500 # ??? ??? ?? ? ?? ???
    database: mysql
    show-sql: true
    open-in-view: true # ??? ????? ?? ??? ???? ??? ??

  application:
    name: altf4
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tutorial?serverTimezone=UTC
    username: ssafy
    password: ssafy

token:
  secret: token # 임의의 문자열
  access-token-expiration-time: 9000000 # 15분 1000(ms) x 60(s) x 15(m) (* 10 : 테스트용 -> 150분)
  refresh-token-expiration-time: 1209600000 # 2주 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)


feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
logging:
  level:
    com.ssafy.altf4: info